config/routes.rb
Rails.application.routes.draw do
  
  get 'forms/user_details'
  get 'forms/address_details'
  get 'forms/office_details'

  get 'forms', to: 'forms#home'
  
  get 'search', to: 'search#search', as: :search

  get '/user_details', to: 'forms#user_details'
  post '/user_details', to: 'forms#create_user_details'
  get '/address_details', to: 'forms#address_details'
  post '/address_details', to: 'forms#create_address_details'
  get '/office_details', to: 'forms#office_details'
  post '/office_details', to: 'forms#create_office_details'

  get 'forms/home'
  devise_for :users
  root to: "forms#home"
  resources :users, only: [:home]
  devise_scope :user do  
  get '/users/sign_out' => 'devise/sessions#destroy' 
  end  
end

app/models/address_details.rb
class AddressDetails < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/office_details.rb
class OfficeDetails < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_details.rb
class UserDetails < ApplicationRecord
    validates :phone_no, format: {
      with: /\A\+\d{2}\s\d{4}\s\d{3}\s\(\d{3}\)\z/,
      message: 'Contact number should match +dd dddd ddd (ddd)'
    }
    validates :firstname, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!

  def home
  def search_bar
    if params[:query].present?
      @result = search(params[:query])
    else
      @result = []
    end
  end  
end  

  def user_details
    @user_details = UserDetails.new(session[:user_details] || {})
  end
  
  def create_user_details
    @user_details = UserDetails.new(user_details1)
    puts "Hello AQ1"

    if @user_details.valid?
      puts "Hello AQ2"
      session[:user_details] = @user_details.attributes
      redirect_to address_details_path
    else
      puts "block else "
      render :user_details 
    end
  end
  
  def address_details
    @address_details = AddressDetails.new(session[:address_details] || {})
  end  

  def create_address_details
   
    @address_details = AddressDetails.new(params[:address_details])
    if @address_details.valid?
      session[:address_details] = @address_details.attributes
      redirect_to office_details_path
    else
      render :address_details
    end
  end   

  def office_details
    @office_details= OfficeDetails.new(session[:office_details]|| {}) 
    
  end   
 

  def create_office_details
    @user_details = UserDetails.new(session[:user_details] || {})
    @address_details = AddressDetails.new(session[:address_details] || {})
    @office_details = OfficeDetails.new(params[:office_details])

    
    if @user_details.save && @address_details.save && @office_details.save
      solr = RSolr.connect(url: 'http://localhost:8983/solr/gettingstarted')
      solr.add([
        @user_details.attributes.merge(id: @user_details.id),  
        @address_details.attributes.merge(id: @address_details.id),
        @office_details.attributes.merge(id: @office_details.id)
          ])
      solr.commit

      session[:user_details]= nil
      session[:address_details]= nil
      session[:office_details]= nil
      
      redirect_to root_path
      puts "saved successfully"
     end     
  end  

  private

  def user_details1
    params.require(:user_details).permit(
    :firstname, :midname, :lastname, :age, :dob, :email, :phone_no,
    :occupation, :degree, :organization, :experience, :org_address,
    :about_us, :interest_rating, :course, :instagram_account, :twitter_account, :facebook_account,
    :cgpa, :father_name, :mother_name, :father_mobile, :mother_mobile, :sibling_details, :suggestions
    )
  end


  def address_details
    params.require(:address_details).permit(
    :name, :phone, :mail,
    :temp_door_no, :temp_street_name, :temp_landmark, :temp_post, :temp_district, :temp_state, :temp_pincode,
    :perm_door_no, :perm_street_name, :perm_landmark, :perm_post, :perm_district, :perm_state, :perm_pincode,
    :ref_name, :ref_contact, :ref_mail
    )
  end
  
  def office_details
    params.require(:office_details).permit(
      :name, :email, :phone_no, :tenth_mark, :twelfth_mark,
      :cgpa, :aadhar_no, :pan_no, :account_no, :no_of_siblings, 
      :first_graduate, :skills, :differently_abled, :completed_graduation
    )
  end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
      @query = params[:query]
      @results = []
  
      if @query.present?
        solr = RSolr.connect(url: 'http://localhost:8983/solr/gettingstarted')
        response = solr.get('select', params: { q: @query })
        @results = response['response']['docs']
      end
    end
  end
  


  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_forms_helper.rb
module FirstFormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/forms/address_details.html.erb
  <div class="container mt-5">
    <h1 class="text-center text-warning">Address Details Form</h1>
    <%= form_with(model: @address_details, url: address_details_path, method: :post) do |form| %>
      <h2>Temporary Address</h2>
      <div class="form-group mb-3">
        <%= form.label :temp_door_no, "Door No" %>
        <%= form.text_field :temp_door_no, class: "form-control",required: true, placeholder: "Enter temporary door number" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :temp_street_name, "Street Name" %>
        <%= form.text_field :temp_street_name, class: "form-control",required: true, placeholder: "Enter temporary street name" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :temp_landmark, "Landmark" %>
        <%= form.text_field :temp_landmark, class: "form-control",required: true, placeholder: "Enter temporary landmark" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :temp_post, "Post" %>
        <%= form.text_field :temp_post, class: "form-control",required: true, placeholder: "Enter temporary post" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :temp_district, "District" %>
        <%= form.text_field :temp_district, class: "form-control",required: true, placeholder: "Enter temporary district" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :temp_state, "State" %>
        <%= form.text_field :temp_state, class: "form-control",required: true, placeholder: "Enter temporary state" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :temp_pincode, "Pincode" %>
        <%= form.text_field :temp_pincode, class: "form-control",required: true, placeholder: "Enter temporary pincode" %>
      </div>

      <h2>Permanent Address</h2>
      <div class="form-group mb-3">
        <%= form.label :perm_door_no, "Door No" %>
        <%= form.text_field :perm_door_no, class: "form-control",required: true, placeholder: "Enter permanent door number" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :perm_street_name, "Street Name" %>
        <%= form.text_field :perm_street_name, class: "form-control",required: true, placeholder: "Enter permanent street name" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :perm_landmark, "Landmark" %>
        <%= form.text_field :perm_landmark, class: "form-control",required: true, placeholder: "Enter permanent landmark" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :perm_post, "Post" %>
        <%= form.text_field :perm_post, class: "form-control",required: true, placeholder: "Enter permanent post" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :perm_district, "District" %>
        <%= form.text_field :perm_district, class: "form-control",required: true, placeholder: "Enter permanent district" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :perm_state, "State" %>
        <%= form.text_field :perm_state, class: "form-control",required: true, placeholder: "Enter permanent state" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :perm_pincode, "Pincode" %>
        <%= form.text_field :perm_pincode, class: "form-control",required: true, placeholder: "Enter permanent pincode" %>
      </div>

      <h2>Person Referred This Course</h2>
      <div class="form-group mb-3">
        <%= form.label :ref_name, "Nominee Name" %>
        <%= form.text_field :ref_name, class: "form-control",required: true, placeholder: "Enter referrer's name" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :ref_contact, "Contact No" %>
        <%= form.text_field :ref_contact, class: "form-control",required: true, placeholder: "Enter referrer's contact number" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :ref_mail, "Email" %>
        <%= form.email_field :ref_mail, class: "form-control",required: true, placeholder: "Enter referrer's email" %>
      </div>

      <%= form.submit "Next", class: "btn btn-warning" %>
      <%= form.button "Clear", type: "reset", class: "btn btn-secondary" %>
    <% end %>
  </div>
</body>

app/views/forms/home.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <div class="d-flex align-items-center justify-content-center">
      <a class="navbar-brand text-light" href="#">My Forms</a>
    </div>
  </div>
  <div class="nav-item">
     <%= form_tag(search_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
      <div class="input-group">
      <%= text_field_tag(:query, params[:query], class: "form-control", placeholder: "Enter id to search") %>
      <%= submit_tag('Search', class: "btn btn-warning my-2 my-sm-0") %>
    </div>
    </div>
    <% end %>
</nav>

<div class="container custom-container mt-5 d-flex justify-content-center" style="max-width: 600px;">
 
  <div class="border rounded p-4 shadow-lg bg-light">
 
    <h1 class="welcome-text text-center">Welcome to My Forms!</h1>
    <p class="welcome-text text-center">Sign in or sign up to get started:</p>
 
    <div class="row">
      <div class="col-md-6">
        <%= link_to "Login", new_user_session_path, class: "btn btn-primary mb-2 btn-block" %>
      </div>
      <div class="col-md-6">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success mb-2 btn-block" %>
      </div>
    </div>
 
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-md-6">
          <%= link_to "Signout", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-block" %>
        </div>
        <div class="col-md-6">
          <div class="input-group">
            <%= link_to user_details_path, class: "btn btn-info btn-block" do %>
              Add Form
            <% end %>
          </div>
        </div>
      </div>
    
    <% end %>
  </div>
</div>

app/views/forms/office_details.html.erb
<div class="container mt-5">
<h1 class="text-center text-warning">Office Details Form</h1>
  <%= form_with(model: @office_details, url: office_details_path, method: :post, local: true) do |form| %>
    <div class="form-group mb-3">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, class: "form-control", required: true, placeholder: "Enter your name" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :email, "Email" %>
      <%= form.email_field :email, class: "form-control", required: true, placeholder: "Enter your email" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :phone_no, "Phone No" %>
      <%= form.text_field :phone_no, class: "form-control", required: true, placeholder: "Enter your phone number" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :tenth_mark, "10th Mark" %>
      <%= form.text_field :tenth_mark, class: "form-control", required: true, placeholder: "Enter your 10th mark" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :twelfth_mark, "12th Mark" %>
      <%= form.text_field :twelfth_mark, class: "form-control", required: true, placeholder: "Enter your 12th mark" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :cgpa, "CGPA" %>
      <%= form.text_field :cgpa, class: "form-control", required: true, placeholder: "Enter your CGPA" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :aadhar_no, "Aadhar No" %>
      <%= form.text_field :aadhar_no, class: "form-control", required: true, placeholder: "Enter your Aadhar number" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :pan_no, "PAN No" %>
      <%= form.text_field :pan_no, class: "form-control", required: true, placeholder: "Enter your PAN number" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :account_no, "Account No" %>
      <%= form.text_field :account_no, class: "form-control", required: true, placeholder: "Enter your account number" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :no_of_siblings, "No of Siblings" %>
      <%= form.number_field :no_of_siblings, class: "form-control", min: 0, required: true, placeholder: "Enter the number of siblings" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :first_graduate, "First Graduate?" %>
      <%= form.select :first_graduate, options_for_select(["Yes", "No"]), class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :skills, "Skills" %>
      <%= form.text_field :skills, class: "form-control", required: true, placeholder: "Enter your skills" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :differently_abled, "Differently Abled?" %>
      <%= form.select :differently_abled, options_for_select(["Yes", "No"]), class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :completed_graduation, "Completed Graduation?" %>
      <%= form.select :completed_graduation, options_for_select(["Yes", "No"]), class: "form-control" %>
    </div>

    <%= form.submit "Submit", class: "btn btn-warning" %>
    <%= form.button "Clear", type: "reset", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/forms/user_details.html.erb
<div class="container mt-5">
  <h1 class="text-center text-warning">User Details Form</h1>
<%= form_with(model: @user_details, url: user_details_path, local: true) do |form| %>

    <div class="form-group mb-3 mb-3">
      <%= form.label :firstname, "First Name", class: "form-label" %>
      <%= form.text_field :firstname, class: "form-control",required:true, placeholder: "Enter your first name" %>
    </div>

    <div class="form-group mb-3 mb-3">
      <%= form.label :midname, "Middle Name", class: "form-label" %>
      <%= form.text_field :midname, class: "form-control",required:true, placeholder: "Enter your middle name" %>
    </div>

    <div class="form-group mb-3 mb-3">
    <%= form.label :lastname, "Last Name", class: "form-label" %>
    <%= form.text_field :lastname, class: "form-control",required:true, placeholder: "Enter your last name" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :age, "Age", class: "form-label" %>
      <%= form.number_field :age, min: 0, class: "form-control",required:true, placeholder: "Enter your age" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :dob, "Date of Birth", class: "form-label" %>
      <%= form.text_field :dob, class: "form-control datepicker",required:true, placeholder: "dd/mm/yyyy" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :email, "Email", class: "form-label" %>
      <%= form.email_field :email, class: "form-control",required:true, placeholder: "Enter your email" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :phone_no, "Phone No", class: "form-label" %>
      <%= form.text_field :phone_no, class: "form-control", placeholder: "Enter your phone number" %>
    </div>

    <div class="form-group mb-3 mb-3">
      <%= form.label :occupation, "Occupation", class: "form-label" %>
      <%= form.select :occupation, ["Student", "Professional"], class: "form-control" %>
    </div>

    <div class="form-group mb-3" id="degree-field">
      <%= form.label :degree, "Degree", class: "form-label" %>
      <%= form.text_field :degree, class: "form-control",required:true, placeholder: "Enter your degree" %>
    </div>

    <div class="form-group mb-3" id="organization-field">
      <%= form.label :organization, "Organization Name", class: "form-label" %>
      <%= form.text_field :organization, class: "form-control",required:true, placeholder: "Enter your organization name" %>
    </div>

    <div class="form-group mb-3" id="experience-field">
      <%= form.label :experience, "Experience", class: "form-label" %>
      <%= form.text_field :experience, class: "form-control",required:true, placeholder: "Enter your experience" %>
    </div>

    <div class="form-group mb-3" id="org-address-field">
      <%= form.label :org_address, "Organization Address", class: "form-label" %>
      <%= form.text_area :org_address, rows: 3, class: "form-control",required:true, placeholder: "Enter your organization address" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :about_us, "How did you hear about us?", class: "form-label" %>
      <%= form.select :about_us, ["Friends", "Family", "Neighbors", "Colleagues", "Others"], class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :interest_rating, "Rate your Interest (1-10)", class: "form-label" %>
      <%= form.number_field :interest_rating, min: 1, max: 10, class: "form-control",required:true, placeholder: "Enter your interest rating" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :course, "Course You Are Joining", class: "form-label" %>
      <%= form.text_field :course, class: "form-control",required:true, placeholder: "Enter the course you are joining" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :instagram_account, "Instagram Account", class: "form-label" %>
      <%= form.text_field :instagram_account, class: "form-control",required:true, placeholder: "Enter your Instagram Account" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :twitter_account, "Twitter Account", class: "form-label" %>
      <%= form.text_field :twitter_account, class: "form-control",required:true, placeholder: "Enter your Twitter Account" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :facebook_account, "Facebook Account", class: "form-label" %>
      <%= form.text_field :facebook_account, class: "form-control",required:true, placeholder: "Enter your Facebook Account" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :cgpa, "CGPA", class: "form-label" %>
      <%= form.number_field :cgpa, step: 0.01, class: "form-control",required:true, placeholder: "Enter your CGPA" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :father_name, "Father's Name", class: "form-label" %>
      <%= form.text_field :father_name, class: "form-control",required:true, placeholder: "Enter your Father's Name" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :mother_name, "Mother's Name", class: "form-label" %>
      <%= form.text_field :mother_name, class: "form-control",required:true, placeholder: "Enter your Mother's Name" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :father_mobile, "Father's Mobile Number", class: "form-label" %>
      <%= form.text_field :father_mobile, class: "form-control",required:true, placeholder: "Enter your Father's Mobile Number" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :mother_mobile, "Mother's Mobile Number", class: "form-label" %>
      <%= form.text_field :mother_mobile, class: "form-control",required:true, placeholder: "Enter your Mother's Mobile Number" %>
    </div>

    <%= form.submit "Next", class: "btn btn-warning" %>
    <%= form.button "Clear", type: "reset", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User_ms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<div class="container mt-5">
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis">Welcome To Datas</h1>
    <p class="fs-5 text-body-secondary">Enter Details To Search</p>
  </div>

  <div class="container d-flex align-items-center justify-content-center">
    <%= form_tag(search_path, method: :get, class: "search-form") do %>
      <div class="inner-form">
        <div class="input-group">
          <%= text_field_tag(:query, params[:query], class: "form-control", placeholder: "Enter ID to search") %>
          <%= text_field_tag(:column_names, params[:column_names], class: "form-control", placeholder: "Enter column names (comma-separated)") %>
          <%= submit_tag('Search', class: "btn btn-warning") %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="container d-flex align-items-center justify-content-center">
  <%= link_to "Home", root_path, class: "btn btn-secondary mt-3" %>
</div>


  <div class="search-results m-5 text-dark p-5">
    <% if @results.present? %>
      <h3>Search Results:</h3>
      <ul>
        <% @results.each do |result| %>
          <% if params[:column_names].present? %>
            <% column_names = params[:column_names].split(",").map(&:strip) %>
            <% column_names.each do |column_name| %>
              <% column_name = column_name.to_s.downcase %>
              <% if result.key?(column_name) %>
                <li>
                  <strong><%= column_name.titleize %>:</strong> <%= result[column_name].first %>
                </li>
                <br>
              <% end %>
            <% end %>
          <% else %>
            <li>
              <strong>Name:</strong> <%= result['name']&.first %>
            </li>
            <br>
            <li>
              <strong>Phone:</strong> <%= result['phone_no']&.first %>
            </li>
            <br>
            <li>
              <strong>Mail:</strong> <%= result['email']&.first %>
            </li>
            <br>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <p>No results found.</p>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<body>
<div class="users">
  <h1>List of Users</h1>
  <ul>
      <% @users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
  </ul>
</div>
</body>
</html>